"""Add recycling centers table

Revision ID: 0389ed378a10
Revises: 
Create Date: 2025-10-23 17:33:57.477845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0389ed378a10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycling_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('operating_hours', sa.String(length=120), nullable=True),
    sa.Column('accepted_types', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recycling_centers')
    # ### end Alembic commands ###
